// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonnelManagement.DataBase.Models;

namespace PersonnelManagement.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210606063913_AddNewTable")]
    partial class AddNewTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Наименование_отдела")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Номер_кабинета")
                        .HasColumnType("int");

                    b.Property<int>("Номер_телефона_отдела")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Holidays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Вид_отпуска")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Дата_окончания_отпуска")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Дата_отпуска")
                        .HasColumnType("datetime2");

                    b.Property<int>("Колл_дней_отпуска")
                        .HasColumnType("int");

                    b.Property<string>("Основание")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Табельный_номер")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Information_about_business_trips", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Колличество_дней")
                        .HasColumnType("int");

                    b.Property<string>("Куда_командирован")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Номер_Приказа")
                        .HasColumnType("int");

                    b.Property<DateTime>("По_дату")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("С_даты")
                        .HasColumnType("datetime2");

                    b.Property<int>("Табельный_номер")
                        .HasColumnType("int");

                    b.Property<string>("Цель_командировки")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Information_about_business_trips");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Information_about_incentives", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Дата")
                        .HasColumnType("datetime2");

                    b.Property<string>("Мотив_поощрения")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Номер_документа")
                        .HasColumnType("int");

                    b.Property<string>("Обоснование")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Сумма")
                        .HasColumnType("int");

                    b.Property<int>("Табельный_номер")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Information_about_incentives");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Information_about_information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Вид_повышения")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Дата_повышения")
                        .HasColumnType("datetime2");

                    b.Property<string>("Наименование_учреждения")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Сведени_о_повышении_квалификации")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Табельный_номер")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Information_about_information");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Information_about_professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Классификация_професии")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Название_профессии")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Information_about_professional");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Layoffs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Дата_увольнения")
                        .HasColumnType("datetime2");

                    b.Property<string>("Причина_увольнения")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Статья")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Табельный_номер")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Layoffs");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Passport_data_of_employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Кем_выдан")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Когда_выдан")
                        .HasColumnType("datetime2");

                    b.Property<int>("Номер")
                        .HasColumnType("int");

                    b.Property<int>("Серия_паспорта")
                        .HasColumnType("int");

                    b.Property<int>("Табельный_номер")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Passport_data_of_employees");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Наименование_должности")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Оклад")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Social_Benefits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Дата_выдачи_документа")
                        .HasColumnType("datetime2");

                    b.Property<string>("Наименование_льгот")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Номер_документа")
                        .HasColumnType("int");

                    b.Property<int>("Табельный_номер")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Social_Benefits");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Дата_приёма")
                        .HasColumnType("datetime2");

                    b.Property<string>("Должность")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Домашний_адрес")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Код_отдела")
                        .HasColumnType("int");

                    b.Property<int>("Код_профессии")
                        .HasColumnType("int");

                    b.Property<long>("Номер_телефона")
                        .HasColumnType("bigint");

                    b.Property<string>("Образование")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Пол")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Семейное_положение")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Стаж_работы")
                        .HasColumnType("int");

                    b.Property<string>("ФИО")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("PersonnelManagement.DataBase.Models.Staffing_schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Код_должности")
                        .HasColumnType("int");

                    b.Property<int>("Код_отдела")
                        .HasColumnType("int");

                    b.Property<int>("Колличество_сотрудников")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Staffing_schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
